# Generated by Django 3.2.5 on 2021-09-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_relationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
