# Generated by Django 3.2.5 on 2021-09-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_relationshipmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelationshipManager',
        ),
    ]
